### ISSUE TITLE
Environment variables support + configurable region?

### ISSUE THREAD

**Issue by fsouza** [omerxx/drone-lambda-plugin#1]
Hey there! Thanks for this project, it's really awesome! I've forked it to add some missing things and was planning to send a PR, but I noticed the diff is crazy right now because I've made the following changes:

1. gofmt
1. add an option for specifying the region
1. support environment variables
1. redact value of environment variables when printing the result
1. vendoring dependencies with dep

The changes are in the fork and you can see them here, but the diff is impracticable: https://github.com/omerxx/drone-lambda-plugin/compare/master...fsouza:master.

Are those changes interesting? If so, how should I send them? Everything in a single PR or one PR per change?

Thanks!

**Comment by omerxx** [comment]
Hey!

Sorry I've missed this issue.. yes, your changes are very much welcomed. I'd love to have them.
